### ISSUE TITLE
points_to_costmap.cpp Bug report

### ISSUE THREAD

**Issue by Tasaki-Lab** [Autoware-AI/core_planning#5]
### Description of the bug

Grids of the cost map generated by costmap_generator are not placed correctlly.
I think the points_to_costmap.cpp has the bug.
points_to_costmap.cpp line 73 - 74:
  int mapped_x_ind = std::ceil(mapped_x);
  int mapped_y_ind = std::ceil(mapped_y);

![1m_costmap_ceil](https://user-images.githubusercontent.com/61577017/85562684-ae470c80-b667-11ea-8f7e-4f5303dbe549.png)

### Additional information

I think a correct code is ...
  int mapped_x_ind = (int)mapped_x;
  int mapped_y_ind = (int)mapped_y;

![1m_costmap_floor](https://user-images.githubusercontent.com/61577017/85562732-b901a180-b667-11ea-9690-a95f09e48ec8.png)

**Comment by JWhitleyWork** [comment]
@Tasaki-Lab I think we might want `static_cast<int>(std::ceil(mapped_x));`. Either way, could you possibly make a Pull Request to address this issue?

**Comment by Tasaki-Lab** [comment]
OK! I'll make a Pull Request.
I close this issue.
