### ISSUE TITLE
waypoint_planner/velocity_set fails to avoid hitting a stationary object while making a turn

### ISSUE THREAD

**Issue by squizz617** [Autoware-AI/core_planning#51]
### Required information:

- Operating system and version: Ubuntu 18.04
- Autoware installation type: Docker image `autoware/autoware:1.14.0-melodic-cuda`, as specified in the Dockerfile of `https://github.com/carla-simulator/carla-autoware` at commit `975b6f3`.
- Autoware version or commit hash - 1.14.0
- ROS distribution and version:
  - ROS Melodic (pre-installed in the docker image)
- ROS installation type:
  - Pre-installed in the docker image

### Description of the bug

* I am running Autoware 1.14.0 (docker image: `autoware/autoware:1.14.0-melodic-cuda`), Carla 0.9.10.1 (docker image: `carlasim/carla:0.9.10.1`) as a simulator and [carla-autoware-bridge](https://github.com/carla-simulator/carla-autoware) at `975b6f3` as a bridge.
* When a curved path is partially blocked by a stationary object, the ego-vehicle stops too late and hits the object.
  * `velocity_set` seems to be setting the stop line based on the location of the obstacle, not considering the width of the ego-vehicle.
  * This is alright if the obstacle is straight ahead. However, at a curve, the stop line is too deep, making the ego-vehicle stop too late.
* Please refer to the diagrams below.
  * ![collision-avoidance-velocity-set](https://user-images.githubusercontent.com/10861633/119192457-31c2d680-ba4e-11eb-89cf-5909154e2815.png)
  * When the object is far enough, ego-vehicle drives without crashing (obviously) - cases (a) and (b).
  * When the object is close enough, ego-vehicle stops (again, obviously) - cases (e) and (f).
  * This bug is only observed when the object is placed at a moderate distance where the ego-vehicle would attempt to turn - cases (c) and (d).

* Please refer to the [Front-facing camera](https://drive.google.com/file/d/1p3Pk9sbz3KBUN4bXgrGzV4etnYjIDRb8/view?usp=sharing), [rear-facing camera](https://drive.google.com/file/d/14O7Zt9e0KDkps5My78vdP5QnPfI4GYB7/view?usp=sharing) and [rosbag](https://drive.google.com/file/d/1YyEg7_V5b-OtEqUoeIUWG_feq8WGrmDL/view?usp=sharing) for detailed analysis.

* velocity_set configuration
```
  <include file='$(find waypoint_planner)/launch/velocity_set.launch'>
    <arg name='use_crosswalk_detection' default='false' />
    <arg name='points_topic' default='points_no_ground' />
    <arg name='velocity_offset' default='4' />
    <arg name='decelerate_vel_min' default='1.3' />
    <arg name='remove_points_upto' default='0.5' />
    <arg name='enable_multiple_crosswalk_detection' default='true' />
    <arg name='stop_distance_obstacle' default='15.0' />
    <arg name='stop_distance_stopline' default='5.0' />
    <arg name='detection_range' default='1.3' />
    <arg name='points_threshold' default='10' />
    <arg name='detection_height_top' default='2.5' />
    <arg name='detection_height_bottom' default='-1.7' />
    <arg name='deceleration_obstacle' default='1.5' />
    <arg name='deceleration_stopline' default='0.6' />
    <arg name='velocity_change_limit' default='15' />
    <arg name='deceleration_range' default='0' />
    <arg name='temporal_waypoints_size' default='100' />
  </include>
```

### Steps to reproduce the bug

* Replay the rosbag file attached above.

### Expected behavior
Ego-vehicle should stop before an obstacle.

### Actual behavior
Ego-vehicle stops late, hitting an obstacle.

**Comment by JWhitleyWork** [comment]
@squizz617 Please see our [support guidelines](https://github.com/Autoware-AI/autoware.ai/wiki/Support-guidelines) for how to get support for Autoware.ai. This should start with a post to [ROS Answers](https://answers.ros.org) with the `autoware` tag. If this results in a confirmed bug, it can then be escelated to an issue here.
