### ISSUE TITLE
Open planner can't make lane change

### ISSUE THREAD

**Issue by Mud-B** [Autoware-AI/core_planning#53]
## Required information:

- Operating system and version: Ubuntu 18.04
- Autoware install From source
- Autoware version: 1.14 
- ROS distribution and version: melodic 1.14.12
- ROS install From source(apt)
- Package or library, if applicable: op_global_planner, op_local_planner

## Description of the bug
open planner doesn't work correctly on vehicle

## Steps to reproduce the bug

1. Launch the runtime_manager node using `roslaunch runtime_manager runtime_manager.launch`
2. start the nodes by runtime_manager(displayed in screenshot below).

## Expected behavior
global planner can help vehicle make lane change by a given goal

## Actual behavior
it doesn't change, and just go to the end of the lane

## Screenshots
- the nodes we launch below:
![0](https://user-images.githubusercontent.com/37743987/147445537-65ea61eb-3129-40f9-b19c-3b1f8ee9a06b.jpg)
- the rviz below:
![1](https://user-images.githubusercontent.com/37743987/147445556-4e2c5aa5-c322-4552-9b6a-d2d473edf249.jpg)
- detailed parameter below:
![2](https://user-images.githubusercontent.com/37743987/147445777-6620ae8a-75a2-4177-aef3-003842628b1b.jpg)
![3](https://user-images.githubusercontent.com/37743987/147445793-8d7b8337-8be4-4a07-96fe-7dd41af138ef.jpg)

**Comment by hatem-darweesh** [comment]
1- Have you tried longer global path > 200 meters , OpenPlanner ignore trajectory change when the local plan is small. 
2- The full support for lane change and bug fixed you can find in this [repository](https://github.com/hatem-darweesh/autoware.ai.openplanner). Two supported releases 1.13 and 1.15 (current Autoware master).

**Comment by Mud-B** [comment]
Thanks for your rapid reply!
1-But can i just resize global path length smaller, or any other way can make it. it's hard to find a &gt; 200 meters path to test.
2-I have tried this repo(1.13) too, but still can't work.



哈呆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Autoware-AI/core_planning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Autoware-AI/core_planning] Open planner can't make lane change (Issue #53)





 
1- Have you tried longer global path &gt; 200 meters , OpenPlanner ignore trajectory change when the local plan is small.
 2- The full support for lane change and bug fixed you can find in this repository. Two supported releases 1.13 and 1.15 (current Autoware master).

**Comment by Mud-B** [comment]
Thanks for your rapid reply!
1-But can i just resize global path length smaller, or any other way can make it. it's hard to find a (>200 meters) path to test.
2-And I have tried this repo(1.13) too, but still can't work.

**Comment by hatem-darweesh** [comment]
Try the Moriyama map. it is included with you can find the link in Autoware.AI docs

**Comment by Mud-B** [comment]
Thanks again for your reply!
Moriyama map is too large, my pc can't run it smoothly, so I find a longer path(>200m) to test. And still can't change lane.
But I found a phenomenon in replaying record bagdata: when vehicle get close to the goal path, the pure_pursuit point make lane change accidently. I have watched your lane change video in youtube, I'm confused how you make it

**Comment by Mud-B** [comment]
It test success in carla cimulator,  thanks for your excelennt work!
