### ISSUE TITLE
How to generate the rollouts from the Autoware op_local_planner package only on the driveable area (Vectormap)

### ISSUE THREAD

**Issue by aforlano** [Autoware-AI/core_planning#54]
Hey everyone, 

I' am currently implementing an obstacle avoidance scenario in CARLA. 

**Required information:**

    Operating system and version: Ubuntu 18.04
    Autoware install From source
    Autoware.ai version: 1.13 
    checked out this versions: 
    - https://github.com/hatem-darweesh/core_planning/tree/openplanner.1.13
    - https://github.com/hatem-darweesh/core_perception/tree/openplanner.1.13
    - https://github.com/hatem-darweesh/common/tree/openplanner.1.13
    ROS distribution and version: melodic
    ROS install From source(apt)
    CARLA Version: 0.9.6
    Package : op_global_planner, op_local_planner

**Steps to Reproduce:** 

Normally start the application. . . 

- ROS: *roscore*
- Simulator: *DISPLAY= ./CarlaUE4.sh -opengl*
- autoware_bridge_with_manual_Control
- ray_ground_filter.launch
- can2odom
- points_downsample
- ndt_matching
- vel_pose_connector
- lidar_euclidean_cluster_detect
- lidar_kf_contour_track
- op_global_planner
- op_local_planner
- pure_pursuit
- twist_filter
- vehiclecmd_to_ackermanndrive
- carla_ackermann_control_node

I load the vector map by using the vector_map_loader node and then i tell the planner to watch for the map data within the autoware rack with the flag "0".

![Screenshot from 2022-06-22 22-45-43](https://user-images.githubusercontent.com/66805713/175222461-1b7db4dc-3bda-4f52-88cb-180795b5ff0f.png)

https://user-images.githubusercontent.com/66805713/175223482-43fbae1d-dc7c-4924-a50c-31052941df54.mp4

The image shows exactly what my problem is, the vehicle routes the car outside the driveable area. How can I tell the local planner to generate the rollouts only inside the Asian vector_map. 

I know there is also some kind of curb detection which unfortunately does not work for me. I think this is because there is no curb data in the sample maps (Town01, ...). Also, this would not solve the problem if there are parts without curbs, e.g. a meadow that should not be driven on either.

Some parameters: 
![op_common_params](https://user-images.githubusercontent.com/66805713/175222348-21d394ca-8ecf-4473-a129-3ce1f67caeb6.png)
![op_motion_predictor_param](https://user-images.githubusercontent.com/66805713/175222368-d8ddb73e-fad2-4abc-be40-bb0c137644f5.png)
![op_trajectory_evaluator_param](https://user-images.githubusercontent.com/66805713/175222378-117a1e85-035d-47d2-a34c-1ccf0f50c286.png)

I hope you can help me here

**Comment by hatem-darweesh** [comment]
Unfortunately you can't. 
Two workarounds: 
1- Add curbs to the map and then enable curb detection in OpenPlanner. 
2- Modify the code to filter generated trajectory according to Lane width and driving direction or driving area from the map.

**Comment by aforlano** [comment]
Hello @hatem-darweesh thank you for your response. 

**To 1:** 
- I imported the Town01 Vectormap into the _Online Vector Map Builder_ tool and added there as seen on the image curb data and exported that map. 

![curb_map](https://user-images.githubusercontent.com/66805713/175384761-aceb74e9-42bf-4c54-8838-3e3650edb363.png)

- As you can see I also get an curb.csv data which contains following data. 

![curb_data](https://user-images.githubusercontent.com/66805713/175384795-c5eb1692-b3a5-40f4-a293-ddb6b5932394.png)

But the problem is that this Curb does not get detected by the op_local_planner detection. 
I have researched how to correctly create curb data, but I have not found anything on this would you have a ready vector map, which already contains curbs data ?

**To 2:** 
- where would be the best position to filter out the trajectories ? would it be inside the _op_trajectory_generator_core.cpp_ ?? 

And finally can you suggest an easier workaround to realize an obstacle avoidance using the autoware.ai framework ?

**Comment by hatem-darweesh** [comment]
Check this fresh [work](https://github.com/hatem-darweesh/autoware.ai.openplanner/issues/5#issuecomment-1164558102):
He did exactly what you are trying to do.

**Comment by aforlano** [comment]
Yes you are right this will solve my problem and I can continue with my development. I am going to also check the second workaround and see how good that works. 

Thank you @hatem-darweesh  so much an have a great day :)
