### ISSUE TITLE
Exported vector map from Vector Map Builder does not work with rosnode wayarea2grid 

### ISSUE THREAD

**Issue by aforlano** [Autoware-AI/core_planning#56]
Hey everyone, 

I just stumbled on an issue with the vector map builder online tool. 
The _wayarea2grid_ node is supposed to read the current vector data and return the driveable area (gray color) like seen on the first image. 

![driveable_area_0](https://user-images.githubusercontent.com/66805713/176321342-a6ac9d9f-81d0-422e-a0a3-a89651167e06.png)

This procedure works fine when using the example vector map "Town01". 

But when I upload the the "Town01" vector map into the online vector map builder tool and I export it directly without editing anything the _wayarea2grid_ node is not working properly and is not displaying the driveable area like seen on the second image. 

![driveable_area_1](https://user-images.githubusercontent.com/66805713/176321373-d913958a-a06e-489a-a443-89193f6be9a3.png)

Did I forget to check or uncheck something inside the online tool ? 
With what has this to do ? 

Ps. Since this problem has to do with getting the drivable area on a map that is used for planning, I am posting this in the planning stack.

**Comment by momala** [comment]
I am also facing the same problem but with kml maps. I tried to modified the Town_1 kml map with assuremapping tools [adding road id and height and width to the curb line.]. I can see the curb blue line in the Rviz. I also found that there is sth publishing in the /map_curb_rviz topic at the beginning, but while the vehicle starts the mission it goes away. I am dealing with the /op_motion_predictor node to check where the problem starts. please let me know if you have any new info.

**Comment by aforlano** [comment]
Actually I solved the described problem by implementing a script that modifies the point.csv. 

Here the problem is that the export of the _vector_map_builder_tool_ [point.csv] has significantly less lines than the Input data therefore a lot of data is missing. 
So I implemented this script that inserts the missing lines and as values for the added line I calculate the meanvalue of the neighboring lines.   
You can use my script but please be aware that it is still under construction :) 


    import pandas as pd

    df = pd.read_csv(r'/home/ai-admin/PycharmProjects/pythonProject/point.csv')

    print(df.columns[0])
    
    for i in range(df.shape[0]):

        if df.values[i+1][0] != df.values[i][0] + 1:
            # Inserting a Row at a Specific Index
            df.loc[i+0.5] = {"PID": i+2,
                             "B": (df.values[i][1] + df.values[i+1][1])/2,
                             "L": (df.values[i][2] + df.values[i+1][2])/2,
                             "H": (df.values[i][3] + df.values[i+1][3])/2,
                             "Bx": (df.values[i][4] + df.values[i+1][4])/2,
                             "Ly": (df.values[i][5] + df.values[i+1][5])/2,
                             "ReF": (df.values[i][6] + df.values[i+1][6])/2,
                             "MCODE1": (df.values[i][7] + df.values[i+1][7])/2,
                             "MCODE2": (df.values[i][8] + df.values[i+1][8])/2,
                             "MCODE3": (df.values[i][9] + df.values[i+1][9])/2}

            df = df.sort_index().reset_index(drop=True)
            i = i + 1

    print("SHAPE OF DF: \n", df.shape[0])
    df_str= str(df)
    print("TYPE OF DF_STR: \n", type(df_str))
    df.to_csv('antonio.csv', index=False)

ps. could you actually help me with this current issue I have ? How did you solve this ? [https://github.com/autowarefoundation/autoware_ai_planning/issues/55](https://github.com/autowarefoundation/autoware_ai_planning/issues/55)
[](https://github.com/autowarefoundation/autoware_ai_planning/issues/55)
